### PR TITLE
Fix the issue that Payload isn't correctly passed to an Adapter.

### LINKED ISSUE #297: FlexboxLayoutManager doesn't work with payloads.
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
FlexboxLayoutManager doesn't work with payloads. I would be glad to change an example to show the bug.

## Expected behavior
The overload of the bind method for the view holder that takes a payload as an extra param is never called when using a payload for the change. Hence the view holder is never refreshed, but it should.

## Version of the flexbox library
0.3.0-alpha3

## Link to code
I didn't do it yet. I just wanted to check if this is a new issue and if you need an example. If so, I can setup an example from a flexbox sample quickly.

### PR DESCRIPTION
**Pull request by thagikura**
The issue was caused because FlexboxLayoutManager returned a scrapped
view holder when it should be returned through the RecyclerView (it's
also returned from the scrapped views, but additional procedures are
processed, such as passing the payload objects if any,
if returned through the RecyclerView).

Fixes #297

### CODE REVIEW

**Comment by stephanenicolas** [comment]
@thagikura : the fix works well ! Thanks. Do you consider to release an alpha 4 including this ?

File: demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java [hunk 1]
```diff
@@ -52,6 +55,8 @@ public FlexItemAdapter(AppCompatActivity activity, FlexboxLayoutManager layoutMa
     public FlexItemViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
         View view = LayoutInflater.from(parent.getContext())
                 .inflate(R.layout.viewholder_flex_item, parent, false);
+
+        Log.d(TAG, "onCreateViewHolder. ViewType: " + viewType + ", Inflated view: " + view);
```
Comment (yaraki) [inline demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java]: Is this log shown for any apps?

File: demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java [hunk 2]
```diff
@@ -63,6 +68,7 @@ public void onBindViewHolder(FlexItemViewHolder holder, int position) {
                 new FlexItemChangedListenerImplRecyclerView(mLayoutManager, this),
                 adapterPosition));
         holder.bindTo(mLayoutParams.get(position));
+        Log.d(TAG, "onBindViewHolder. Holder: " + holder + ", Position: " + position);
```
Comment (yaraki) [inline demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java]: Is this log shown for any apps?

File: flexbox/src/androidTest/java/com/google/android/flexbox/test/TestAdapter.java [hunk 3]
```diff
@@ -67,6 +76,14 @@ void addItem(FlexboxLayoutManager.LayoutParams flexItem) {
         notifyItemInserted(mLayoutParams.size() - 1);
     }
 
+    void changeItemWithPayload(int position, Object payload) {
+        notifyItemChanged(position, payload);
+    }
+
+    List<Object> getPayloads() {
+        return Collections.unmodifiableList(mReceivedPayloads);
```
Comment (yaraki) [inline flexbox/src/androidTest/java/com/google/android/flexbox/test/TestAdapter.java]: This seems to be API level 24. Is it alright?
https://developer.android.com/reference/java/util/Collections.html#unmodifiableList(java.util.List<? extends T>)

File: demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java (hunk 1 above)
Comment (thagikura) [inline demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java]: It's shown only in the demo app, but used only for the development purpose. Deleted.

File: demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java (hunk 2 above)
Comment (thagikura) [inline demo-playground/src/main/java/com/google/android/flexbox/recyclerview/FlexItemAdapter.java]: It's shown only in the demo app, but used only for the development purpose. Deleted.

File: flexbox/src/androidTest/java/com/google/android/flexbox/test/TestAdapter.java (hunk 3 above)
Comment (thagikura) [inline flexbox/src/androidTest/java/com/google/android/flexbox/test/TestAdapter.java]: Good point. Changed this part to return a new ArrayList

**Comment by thagikura** [comment]
Thanks! PTAL.

**Comment by thagikura** [comment]
@stephanenicolas yes, I'm going to include this in the next release.
