### PR TITLE
Fixes the issue that only single line was displayed with nested Recyc…

### LINKED ISSUE #290: RecyclerView in RecyclerView with FlexboxLayoutManager only show one line
I use a recyclerview(just call it the **ARecyclerView** with LinearLayoutManager ) and make another recyclerview(just call it the **BRecyclerView** with FlexboxLayoutManager) as the item of ARecyclerView**.

But after I call notifyDataSetChanged() ,the **BRecyclerView** only show one line whenever the data change. What I want is it should show more than one line because the BRecyclerView don't show all data.
The BRecyclerView layout is 
```xml
<android.support.v7.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/training_term_and_lesson_item_list"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    tools:listitem="@layout/training_item_venue_filter" />
```

and the item of BRecyclerView is
```xml
<?xml version="1.0" encoding="utf-8"?>
<CheckBox xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/training_item_venue_filter_venue_name"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginEnd="20dp"
    android:layout_marginRight="20dp"
    android:layout_marginTop="15dp"
    android:background="@drawable/commonsdk_bg_checkbox_corner_5"
    android:button="@null"
    android:gravity="center"
    android:minWidth="80dp"
    android:paddingBottom="7dp"
    android:paddingEnd="13dp"
    android:paddingLeft="13dp"
    android:paddingRight="13dp"
    android:paddingStart="13dp"
    android:paddingTop="7dp"
    android:textColor="@drawable/commonsdk_checkbox_text_color_normal_white"
    android:textSize="@dimen/commonsdk_super_small_text"
    tools:text="Hello World" />
```

## Expected behavior
What I want it show is 

## Version of the flexbox library
 0.3.0-alpha3*

### PR DESCRIPTION
**Pull request by thagikura**
…lerViews

where the inner RecycerView's adapter is FlexboxLayoutManager with FlexWrap is
set to wrap.

This was caused because height 0 was passed from the parent RecyclerView
if the layout_height is specified as wrap_content, thus
FlexboxLayoutManager didn't calculate the entire items for its flex lines.

This fixes #290

### CODE REVIEW

File: flexbox/src/main/java/com/google/android/flexbox/FlexboxLayoutManager.java [hunk 1]
```diff
@@ -189,8 +206,9 @@ public FlexboxLayoutManager(@FlexDirection int flexDirection) {
      * @param flexDirection the flex direction attribute
      * @param flexWrap      the flex wrap attribute
      */
-    public FlexboxLayoutManager(@FlexDirection int flexDirection,
+    public FlexboxLayoutManager(Context context, @FlexDirection int flexDirection,
             @FlexWrap int flexWrap) {
+        setDisplayMetrics(context);
```
Comment (yaraki) [inline flexbox/src/main/java/com/google/android/flexbox/FlexboxLayoutManager.java]: This way, the values are not updated when android:configChanges="..." is set for the activity. What about calling this every time but only when necessary? We need these values only when the size is infinite.

Comment (thagikura) [inline flexbox/src/main/java/com/google/android/flexbox/FlexboxLayoutManager.java]: Deleted the mDisplayWidth/mDisplayLength memebers. Now FlexboxLayoutManager has a context as its member and retrieves the display length when needed.
